# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='birds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird_name', models.CharField(blank=True, max_length=210, null=True)),
                ('bird_desc', models.TextField(blank=True, null=True)),
                ('bird_location', models.CharField(blank=True, max_length=210, null=True)),
            ],
        ),
    ]
