# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdy', '0002_auto_20170726_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='bird_desc',
            field=models.TextField(blank=True, default='a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bird',
            name='bird_location',
            field=models.CharField(blank=True, default='a', max_length=210),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bird',
            name='bird_name',
            field=models.CharField(blank=True, default='a', max_length=210),
            preserve_default=False,
        ),
    ]
