# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdy', '0003_auto_20170728_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bird',
            old_name='bird_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='bird',
            old_name='bird_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='bird',
            old_name='bird_name',
            new_name='name',
        ),
    ]
