# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdy', '0004_auto_20170728_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
